## Build the docs by cd'ing into docs and doing: 
## quarto render .
## python -m quartodoc build
## python gen_api_custom.py
project:
  type: website
  output-dir: ../docs
  
metadata-files:
  - _sidebar.yml

quartodoc: 
  package: simplextree
  title: API Reference    # API only 
  dir: pages/reference    # API only 
  style: pkgdown          # API only
  sidebar: _sidebar.yml 
  
  renderer: 
    style: _renderer.py
    show_signature: true
    show_signature_annotations: true
    display_name: name 
  
  ## NOTE: THIS IS NOT THE SIDEBAR 
  sections: 
    - title: Simplex Tree 
      contents: 
        - SimplexTree
    - title: Union Find
      contents: 
        - UnionFind

website:
  search: 
    location: sidebar
    type: textbox
  navbar:
    left: 
      - text: simplextree
        href: pages/index.html
    background: light
    right: 
      - icon: github
        href: https://github.com/peekxc/simplextree-py
    pinned: false  
    search: false       
  sidebar:
    style: "docked"
    pinned: false
    align: center 
    search: true
    border: true 
    collapse-level: 2
    contents: 
      - text: Quick start 
        href: pages/quickstart.qmd
      - text: Overview 
        href: pages/overview.qmd
      - section: API Reference
        href: pages/reference/index.qmd
        contents:
          - name: SimplexTree 
            text: Simplex Tree
            href: pages/reference/SimplexTree.SimplexTree.qmd
          - name: UnionFind 
            text: Union Find
            href: pages/reference/UnionFind.UnionFind.qmd

  page-navigation: true
  reader-mode: true
  page-footer: 
    center: "Copyright 2023, Matthew Piekenbrock" 
    border: true

latex-auto-install: true 

execute:
  cache: true

theme: 
  light: flatly
  dark: darkly

format:
  html:
    toc: true # for scrollspy! 
    toc-expand: 3
    anchor-selections: true 
    code-fold: false
    smooth-scroll: true
    html-math-method: katex
    code-overflow: wrap 
    highlight-style: printing 
    # fontsize: 14px
    # linestretch: 1.6
    margin-top: "4px" 
    css: /static/styles.css
    # monobackgroundcolor: "#d3d3d357"
# out_index: pages/index.qmd
# sphinx-build . ./_build/html -b html