## Build the docs by cd'ing into docs and doing: 
## quarto render .
## python -m quartodoc build
## python gen_api_custom.py
project:
  type: website
  output-dir: ../docs
  
metadata-files:
  - _sidebar.yml

quartodoc: 
  package: simplextree
  title: API Reference    # API only 
  dir: pages/reference    # API only 
  style: pkgdown         # API only
  sidebar: _sidebar.yml 
  
  # renderer: 
  #   style: _renderer.py
  #   show_signature: true
  #   show_signature_annotations: true
  #   display_name: name 
  parser: google

  ## NOTE: THIS IS NOT THE SIDEBAR 
  sections: 
    - title: Simplex Tree 
      contents: 
        - name: SimplexTree
          children: separate
          include_empty: false
          members:
            - SimplexTree.insert
            - SimplexTree.remove
            - SimplexTree.find
            - SimplexTree.adjacent
            - SimplexTree.collapse
            - SimplexTree.contract
            - SimplexTree.vertex_collapse
            - SimplexTree.degree
            - SimplexTree.traverse
            - SimplexTree.cofaces
            # - Simplextree.coface_root
            - SimplexTree.skeleton
            - SimplexTree.simplices
            - SimplexTree.faces
            - SimplexTree.maximal
            - SimplexTree.link
            - SimplexTree.expand
            - SimplexTree.reindex
            - SimplexTree.dim
            - SimplexTree.card
            - SimplexTree.print
            - SimplexTree.__iter__
            - SimplexTree.__contains__
            - SimplexTree.__len__     
    - title: UnionFind
      contents: 
        - UnionFind

website:
  search: 
    location: sidebar
    type: textbox
  navbar:
    background: light
    left: 
      - text: simplextree
        href: pages/index.qmd
    right: 
      - icon: github
        href: https://github.com/peekxc/simplextree-py
    pinned: false  
    search: false       
  sidebar:
    style: "docked"
    pinned: false
    align: center 
    search: true
    border: true 
    collapse-level: 2
    contents: 
      - text: Overview 
        href: pages/overview.qmd
      - text: Quick start 
        href: pages/quickstart.qmd
      - section: API Reference
        href: pages/reference/index.qmd
        contents:
          - name: SimplexTree 
            text: Simplex Tree
            href: pages/reference/SimplexTree.qmd
          - name: UnionFind 
            text: Union Find
            href: pages/reference/UnionFind.qmd

  page-navigation: true
  reader-mode: true
  page-footer: 
    center: "Copyright 2024, Matthew Piekenbrock" 
    border: true
  body-footer: |
    <script data-goatcounter="https://peekxc.goatcounter.com/count" async src="//gc.zgo.at/count.js"></script>

latex-auto-install: true 

execute:
  cache: true

theme: 
  light: flatly
  dark: darkly

format:
  html:
    toc: true # for scrollspy! 
    toc-expand: 3
    anchor-selections: true 
    code-fold: false
    smooth-scroll: true
    html-math-method: katex
    code-overflow: wrap 
    highlight-style: printing 
    # fontsize: 14px
    # linestretch: 1.6
    margin-top: "4px" 
    css: /static/styles.css
    # monobackgroundcolor: "#d3d3d357"
out_index: pages/index.qmd
# sphinx-build . ./_build/html -b html